language: c

os:
 - linux
 - linux-ppc64le

# NB: This is just the distro used for the container host
dist: bionic
services: docker

cache: ccache

env:
    jobs:
      - RUN_ON_CONTAINER=ubuntu-18.04
      - RUN_ON_CONTAINER=ubuntu-20.04
      - RUN_ON_CONTAINER=ubuntu-latest
      - RUN_ON_CONTAINER=centos7
      - RUN_ON_CONTAINER=fedora32
      - RUN_ON_CONTAINER=fedora-rawhide
      - RUN_ON_CONTAINER=debian-unstable
      - RUN_ON_CONTAINER=docs
    global:
        # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
        #   via the "travis encrypt" command using the project repo's public key

jobs:
  allow_failures:
    - env: RUN_ON_CONTAINER=fedora-rawhide
    - env: RUN_ON_CONTAINER=debian-unstable
  exclude:
    - os: linux-ppc64le
      env: RUN_ON_CONTAINER=centos7
    - os: linux-ppc64le
      env: RUN_ON_CONTAINER=docs

script:
    - docker build --pull -t ${RUN_ON_CONTAINER} -f opal-ci/Dockerfile-${RUN_ON_CONTAINER} . &&
      docker run --volume $HOME/.ccache:/root/.ccache --volume `pwd`:/build --rm -t $RUN_ON_CONTAINER bash -c "./opal-ci/build-${RUN_ON_CONTAINER}.sh";

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # set in travis-ci.org dashboard, marked secure
  local_dir: "doc/_build/ghpages"
  on:
    branch: master
    condition: "$RUN_ON_CONTAINER = docs"
